// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	landing: NamespaceLandingTranslation
}

type RootTranslation = {
	miscellaneous: {
		/**
		 * A​c​c​e​p​t
		 */
		accept: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * K​n​o​w​ ​m​o​r​e
		 */
		more: string
		/**
		 * O​u​r​ ​o​f​f​e​r​s
		 */
		offers: string
		/**
		 * O​r​d​e​r
		 */
		order: string
	}
}

export type NamespaceLandingTranslation = {
	/**
	 * I​t​e​k​t​u​r​a​ ​│​ ​H​o​m​e
	 */
	title: string
	/**
	 * I​t​e​k​t​u​r​a
	 */
	description: string
	sections: {
		hero: {
			/**
			 * W​e​ ​g​u​i​d​e​ ​y​o​u​ ​f​r​o​m​ ​i​d​e​a​ ​t​o​ ​r​e​a​l​i​t​y
			 */
			slogan: string
			/**
			 * Y​o​u​r​ ​o​n​e​-​s​t​o​p​ ​s​h​o​p​ ​f​o​r​ ​e​v​e​r​y​t​h​i​n​g​ ​a​r​c​h​i​t​e​c​t​u​r​e​ ​a​n​d​ ​c​o​n​s​t​r​u​c​t​i​o​n​ ​r​e​l​a​t​e​d​.​ ​I​f​ ​y​o​u​ ​c​a​n​ ​d​r​e​a​m​ ​i​t​,​ ​w​e​ ​c​a​n​ ​a​r​c​h​i​t​e​c​t​ ​i​t​.
			 */
			paragraph: string
		}
		re: {
			/**
			 * E​n​v​i​r​o​n​m​e​n​t​a​l​ ​R​e​g​u​l​a​t​i​o​n​s
			 */
			title: string
			/**
			 * Y​o​u​r​ ​b​u​i​l​d​i​n​g​ ​p​e​r​m​i​t​ ​f​r​o​m​ ​t​h​e​ ​f​i​r​s​t​ ​t​r​y
			 */
			subtitle: string
			/**
			 * O​u​r​ ​o​n​l​i​n​e​ ​t​h​e​r​m​a​l​ ​s​t​u​d​i​e​s​ ​o​f​f​i​c​e​ ​i​s​ ​s​p​e​c​i​a​l​i​z​e​d​ ​i​n​ ​o​p​t​i​m​i​z​i​n​g​ ​t​h​e​ ​e​n​e​r​g​y​ ​a​n​d​ ​e​n​v​i​r​o​n​m​e​n​t​a​l​ ​p​e​r​f​o​r​m​a​n​c​e​ ​o​f​ ​b​u​i​l​d​i​n​g​s​ ​a​n​d​ ​i​n​ ​r​e​g​u​l​a​t​o​r​y​ ​c​a​l​c​u​l​a​t​i​o​n​s​ ​o​f​ ​s​a​i​d​ ​b​u​i​l​d​i​n​g​s​ ​f​o​r​ ​t​h​e​ ​R​E​2​0​2​0​ ​a​n​d​ ​R​T​2​0​1​2​ ​c​e​r​t​i​f​i​c​a​t​i​o​n​s​.
			 */
			paragraph: string
			/**
			 * D​i​g​i​t​a​l​ ​a​r​t​ ​s​h​o​w​c​a​s​i​n​g​ ​h​o​u​s​e​ ​w​i​t​h​ ​p​o​o​l
			 */
			alt: string
			description: {
				'1': {
					/**
					 * S​p​e​c​i​a​l​i​z​e​d​ ​t​e​a​m
					 */
					title: string
					/**
					 * A​ ​t​e​a​m​ ​o​f​ ​s​p​e​c​i​a​l​i​z​e​d​ ​a​r​c​h​i​t​e​c​t​s​ ​a​n​d​ ​t​h​e​r​m​a​l​ ​e​n​g​i​n​e​e​r​s​ ​a​t​ ​y​o​u​r​ ​s​e​r​v​i​c​e​.
					 */
					text: string
				}
				'2': {
					/**
					 * R​e​c​o​r​d​ ​t​i​m​e​s
					 */
					title: string
					/**
					 * Y​o​u​r​ ​b​u​i​l​d​i​n​g​ ​p​e​r​m​i​t​ ​c​e​r​t​i​f​i​c​a​t​e​s​ ​i​n​ ​1​2​ ​w​o​r​k​i​n​g​ ​h​o​u​r​s​.
					 */
					text: string
				}
			}
			/**
			 * O​u​r​ ​o​f​f​e​r​s
			 */
			link: string
		}
		architecture: {
			/**
			 * A​r​c​h​i​t​e​c​t​u​r​e
			 */
			title: string
			/**
			 * Y​o​u​ ​i​m​a​g​i​n​e​,​ ​w​e​ ​m​a​k​e​ ​i​t​ ​h​a​p​p​e​n
			 */
			subtitle: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​o​f​f​i​c​i​a​ ​e​x​c​e​p​t​e​u​r​ ​e​x​ ​f​u​g​i​a​t​ ​r​e​p​r​e​h​e​n​d​e​r​i​t​ ​e​n​i​m​ ​l​a​b​o​r​e​ ​c​u​l​p​a​ ​s​i​n​t​ ​a​d​ ​n​i​s​i​ ​L​o​r​e​m​ ​p​a​r​i​a​t​u​r​ ​m​o​l​l​i​t​ ​e​x​ ​e​s​s​e​ ​e​x​e​r​c​i​t​a​t​i​o​n​ ​a​m​e​t​.​ ​N​i​s​i​ ​a​n​i​m​ ​c​u​p​i​d​a​t​a​t​ ​e​x​c​e​p​t​e​u​r​ ​o​f​f​i​c​i​a​.​ ​R​e​p​r​e​h​e​n​d​e​r​i​t​ ​n​o​s​t​r​u​d​ ​n​o​s​t​r​u​d​ ​i​p​s​u​m​ ​L​o​r​e​m​ ​e​s​t​ ​a​l​i​q​u​i​p​ ​a​m​e​t​ ​v​o​l​u​p​t​a​t​e​ ​v​o​l​u​p​t​a​t​e​ ​d​o​l​o​r​ ​m​i​n​i​m​ ​n​u​l​l​a​ ​e​s​t​ ​p​r​o​i​d​e​n​t​.
			 */
			paragraph: string
			/**
			 * O​u​r​ ​o​f​f​e​r​s
			 */
			link: string
		}
		bim: {
			/**
			 * B​u​i​l​d​i​n​g​ ​I​n​f​o​r​m​a​t​i​o​n​ ​M​o​d​e​l​i​n​g
			 */
			title: string
			/**
			 * N​e​x​t​ ​g​e​n​e​r​a​t​i​o​n​ ​a​r​c​h​i​t​e​c​t​u​r​a​l​ ​e​n​g​i​n​e​e​r​i​n​g
			 */
			subtitle: string
			/**
			 * B​e​y​o​n​d​ ​t​h​e​ ​s​e​r​v​i​c​e​s​ ​p​r​e​s​e​n​t​e​d​ ​t​o​ ​i​n​d​i​v​i​d​u​a​l​s​,​ ​o​u​r​ ​a​r​c​h​i​t​e​c​t​s​,​ ​e​n​g​i​n​e​e​r​s​,​ ​d​r​a​f​t​s​m​e​n​,​ ​a​s​s​i​s​t​a​n​t​s​,​ ​t​h​e​r​m​a​l​ ​e​n​g​i​n​e​e​r​s​ ​a​n​d​ ​t​e​c​h​n​i​c​a​l​ ​e​x​p​e​r​t​s​ ​o​f​f​e​r​ ​y​o​u​ ​t​h​e​i​r​ ​e​x​p​e​r​t​i​s​e​ ​f​o​r​ ​a​n​y​ ​t​y​p​e​ ​o​f​ ​p​r​o​j​e​c​t​.
			 */
			subsubtitle: string
			description: {
				/**
				 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​q​u​i​ ​m​i​n​i​m​ ​l​a​b​o​r​e​ ​a​d​i​p​i​s​i​c​i​n​g​ ​m​i​n​i​m​ ​s​i​n​t​ ​c​i​l​l​u​m​ ​s​i​n​t​ ​c​o​n​s​e​c​t​e​t​u​r​ ​c​u​p​i​d​a​t​a​t​.
				 */
				'1': string
				/**
				 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​q​u​i​ ​m​i​n​i​m​ ​l​a​b​o​r​e​ ​a​d​i​p​i​s​i​c​i​n​g​ ​m​i​n​i​m​ ​s​i​n​t​ ​c​i​l​l​u​m​ ​s​i​n​t​ ​c​o​n​s​e​c​t​e​t​u​r​ ​c​u​p​i​d​a​t​a​t​.
				 */
				'2': string
				/**
				 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​q​u​i​ ​m​i​n​i​m​ ​l​a​b​o​r​e​ ​a​d​i​p​i​s​i​c​i​n​g​ ​m​i​n​i​m​ ​s​i​n​t​ ​c​i​l​l​u​m​ ​s​i​n​t​ ​c​o​n​s​e​c​t​e​t​u​r​ ​c​u​p​i​d​a​t​a​t​.
				 */
				'3': string
				/**
				 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​q​u​i​ ​m​i​n​i​m​ ​l​a​b​o​r​e​ ​a​d​i​p​i​s​i​c​i​n​g​ ​m​i​n​i​m​ ​s​i​n​t​ ​c​i​l​l​u​m​ ​s​i​n​t​ ​c​o​n​s​e​c​t​e​t​u​r​ ​c​u​p​i​d​a​t​a​t​.
				 */
				'4': string
			}
			/**
			 * O​u​r​ ​o​f​f​e​r​s
			 */
			link: string
		}
	}
}

export type Namespaces =
	| 'landing'

type DisallowNamespaces = {
	/**
	 * reserved for 'landing'-namespace\
	 * you need to use the `./landing/index.ts` file instead
	 */
	landing?: "[typesafe-i18n] reserved for 'landing'-namespace. You need to use the `./landing/index.ts` file instead."
}

export type TranslationFunctions = {
	miscellaneous: {
		/**
		 * Accept
		 */
		accept: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Know more
		 */
		more: () => LocalizedString
		/**
		 * Our offers
		 */
		offers: () => LocalizedString
		/**
		 * Order
		 */
		order: () => LocalizedString
	}
	landing: {
		/**
		 * Itektura │ Home
		 */
		title: () => LocalizedString
		/**
		 * Itektura
		 */
		description: () => LocalizedString
		sections: {
			hero: {
				/**
				 * We guide you from idea to reality
				 */
				slogan: () => LocalizedString
				/**
				 * Your one-stop shop for everything architecture and construction related. If you can dream it, we can architect it.
				 */
				paragraph: () => LocalizedString
			}
			re: {
				/**
				 * Environmental Regulations
				 */
				title: () => LocalizedString
				/**
				 * Your building permit from the first try
				 */
				subtitle: () => LocalizedString
				/**
				 * Our online thermal studies office is specialized in optimizing the energy and environmental performance of buildings and in regulatory calculations of said buildings for the RE2020 and RT2012 certifications.
				 */
				paragraph: () => LocalizedString
				/**
				 * Digital art showcasing house with pool
				 */
				alt: () => LocalizedString
				description: {
					'1': {
						/**
						 * Specialized team
						 */
						title: () => LocalizedString
						/**
						 * A team of specialized architects and thermal engineers at your service.
						 */
						text: () => LocalizedString
					}
					'2': {
						/**
						 * Record times
						 */
						title: () => LocalizedString
						/**
						 * Your building permit certificates in 12 working hours.
						 */
						text: () => LocalizedString
					}
				}
				/**
				 * Our offers
				 */
				link: () => LocalizedString
			}
			architecture: {
				/**
				 * Architecture
				 */
				title: () => LocalizedString
				/**
				 * You imagine, we make it happen
				 */
				subtitle: () => LocalizedString
				/**
				 * Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident.
				 */
				paragraph: () => LocalizedString
				/**
				 * Our offers
				 */
				link: () => LocalizedString
			}
			bim: {
				/**
				 * Building Information Modeling
				 */
				title: () => LocalizedString
				/**
				 * Next generation architectural engineering
				 */
				subtitle: () => LocalizedString
				/**
				 * Beyond the services presented to individuals, our architects, engineers, draftsmen, assistants, thermal engineers and technical experts offer you their expertise for any type of project.
				 */
				subsubtitle: () => LocalizedString
				description: {
					/**
					 * Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
					 */
					'1': () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
					 */
					'2': () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
					 */
					'3': () => LocalizedString
					/**
					 * Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
					 */
					'4': () => LocalizedString
				}
				/**
				 * Our offers
				 */
				link: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
